### ISSUE TITLE
preset-importer shields don't match stock RO shields

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROHeatshields#6]
Nothing new, just capturing this so it doesn't get forgotten.

Full story: https://discord.com/channels/319857228905447436/663102368887472156/904161765691117598

Short version: with preset-importer branch, a ROH shield using the Lunar config appears to be much more fragile than a "stock" lunar shield. Preliminary theory is that it correctly imports what goes into ModuleAblator, but not what applies to the part itself (thermal mass, etc)

**Comment by siimav** [comment]
Should be fixed by https://github.com/KSP-RO/ROHeatshields/commit/ae72290ae371b4607a9173fc65b03a7d1b019e0e
