### ISSUE TITLE
Adjustable heatshield changes the amount of ablator after launch

### ISSUE THREAD

**Issue by ghost** [KSP-RO/ROHeatshields#8]
Adjustable heatshield with less than maximum amount of ablator set in VAB has maximum ablator when the craft is launched.

**Comment by lpgagnon** [comment]
Standecco fixed this a long time ago, did the fix never make it out of that fork, or did it get lost?

https://discord.com/channels/319857228905447436/663102368887472156/788846732821004298
https://github.com/dgfl-gh/ROHeatshields/commit/7940baa00cd785024a786e50d28ab4f71f1ac49a

**Comment by lpgagnon** [comment]
The fix does seem to have been included in https://github.com/KSP-RO/ROHeatshields/commit/4fac3fcde327b1f48539357d255ac23a62f410de so looks like something re-broke later

**Comment by siimav** [comment]
@lpgagnon btw, did you personally (or anybody else) confirm that this is a general issue? Or does it happen with only certain configs or under specific circumstances?

**Comment by lpgagnon** [comment]
I hadn't (was only digging through the history), but I have now. It's a general issue; happens to all configs with no special steps involved. Place part, select config with ablator, change ablator amount, start sim. Check ablator in flight scene, it's full.

**Comment by marsh1832** [comment]
It happens to me with almost all rockets, but I was running on an older version of rp1 for the RiS so I didn't think too much of it. It doesn't seem to happen on every shield, but most of them. I can try to look a little closer about which ones are not effected. For me it changes on the flight scene change. For example if I hyperedit the extra ablator away, make a save, and then load the save, the ablator returns.
